import React, { useState } from 'react';
import Navbar from './Navbar';
import ResultsDisplay from './ResultsDisplay';
import MetricsDashboard from './MetricsDashboard';
import api from '../services/api';
import toast from 'react-hot-toast';
import { jsPDF } from 'jspdf';

const CodeAnalyzer = () => {
  const [code, setCode] = useState(`// Paste your Java code here...

public class Example {
    public void riskyMethod() {
        String value = null;
        System.out.println(value.length());
    }
}`);
  const [loading, setLoading] = useState(false);
  const [analysisData, setAnalysisData] = useState(null);
  const [metricsData, setMetricsData] = useState(null);
  const [activeView, setActiveView] = useState('issues');
  const [stats, setStats] = useState({
    critical: 0,
    warning: 0,
    info: 0,
    total: 0
  });

  const analyzeCode = async () => {
    if (!code.trim()) {
      toast.error('Please enter some Java code to analyze');
      return;
    }

    setLoading(true);
    setActiveView('issues');

    try {
      const response = await api.post('/analyze', { code });
      const data = response.data;
      
      setAnalysisData(data);
      setStats({
        critical: data.critical?.length || 0,
        warning: data.warning?.length || 0,
        info: data.info?.length || 0,
        total: data.totalIssues || 0
      });
      
      toast.success('Analysis completed successfully!');
    } catch (error) {
      console.error('Analysis error:', error);
      toast.error(error.response?.data?.message || 'Analysis failed');
    } finally {
      setLoading(false);
    }
  };

  const showMetrics = async () => {
    if (!code.trim()) {
      toast.error('Please enter some Java code to analyze');
      return;
    }

    setLoading(true);
    setActiveView('metrics');

    try {
      const response = await api.post('/metrics', { code });
      const data = response.data;
      
      setMetricsData(data);
      toast.success('Metrics calculated successfully!');
    } catch (error) {
      console.error('Metrics error:', error);
      toast.error(error.response?.data?.message || 'Failed to calculate metrics');
    } finally {
      setLoading(false);
    }
  };

  const clearAll = () => {
    setCode('');
    setAnalysisData(null);
    setMetricsData(null);
    setActiveView('issues');
    setStats({ critical: 0, warning: 0, info: 0, total: 0 });
    toast.success('Cleared all data');
  };

  const downloadPDF = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    let yPos = 20;

    // Header
    doc.setFillColor(102, 126, 234);
    doc.rect(0, 0, pageWidth, 40, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont(undefined, 'bold');
    doc.text('☕ Java Code Review Report', pageWidth / 2, 20, { align: 'center' });
    
    doc.setFontSize(10);
    doc.setFont(undefined, 'normal');
    const currentDate = new Date().toLocaleDateString('en-US', { 
      year: 'numeric', 
      month: 'long', 
      day: 'numeric' 
    });
    doc.text(`Generated: ${currentDate}`, pageWidth / 2, 30, { align: 'center' });

    yPos = 50;
    doc.setTextColor(0, 0, 0);

    if (activeView === 'metrics' && metricsData) {
      generateMetricsPDF(doc, pageWidth, pageHeight, yPos, metricsData);
    } else if (activeView === 'issues' && analysisData) {
      generateIssuesPDF(doc, pageWidth, pageHeight, yPos, analysisData);
    }

    // Footer
    const totalPages = doc.internal.pages.length - 1;
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text(`Page ${i} of ${totalPages}`, pageWidth / 2, pageHeight - 10, { align: 'center' });
      doc.text('Generated by Java Code Analyzer Pro', pageWidth / 2, pageHeight - 5, { align: 'center' });
    }

    doc.save(`code-review-${Date.now()}.pdf`);
  };

  const generateMetricsPDF = (doc, pageWidth, pageHeight, yPos, metrics) => {
    doc.setFontSize(16);
    doc.setFont(undefined, 'bold');
    doc.text('📊 Code Metrics Summary', 20, yPos);
    yPos += 10;

    doc.setDrawColor(102, 126, 234);
    doc.setLineWidth(0.5);
    doc.rect(15, yPos, pageWidth - 30, 80);
    yPos += 10;

    doc.setFontSize(11);
    doc.setFont(undefined, 'normal');
    
    doc.text(`Total Lines: ${metrics.totalLines || 0}`, 25, yPos);
    doc.text(`Classes: ${metrics.classCount || 0}`, pageWidth / 2 + 10, yPos);
    yPos += 8;
    
    doc.text(`Code Lines: ${metrics.codeLines || 0}`, 25, yPos);
    doc.text(`Methods: ${metrics.methodCount || 0}`, pageWidth / 2 + 10, yPos);
    yPos += 8;
    
    doc.text(`Comment Lines: ${metrics.commentLines || 0}`, 25, yPos);
    doc.text(`Public Methods: ${metrics.publicMethodCount || 0}`, pageWidth / 2 + 10, yPos);
    yPos += 8;
    
    doc.text(`Blank Lines: ${metrics.blankLines || 0}`, 25, yPos);
    doc.text(`Private Methods: ${metrics.privateMethodCount || 0}`, pageWidth / 2 + 10, yPos);
    yPos += 8;
    
    doc.text(`Comment Percentage: ${(metrics.commentPercentage || 0).toFixed(1)}%`, 25, yPos);
    yPos += 15;

    doc.setFontSize(16);
    doc.setFont(undefined, 'bold');
    doc.text('🎯 Quality Assessment', 20, yPos);
    yPos += 10;

    doc.setFillColor(240, 240, 240);
    doc.rect(15, yPos, pageWidth - 30, 35, 'F');
    yPos += 10;

    doc.setFontSize(14);
    doc.setTextColor(102, 126, 234);
    doc.text(`Quality Score: ${metrics.qualityScore || 0}/100`, pageWidth / 2, yPos, { align: 'center' });
    yPos += 10;

    doc.setFontSize(18);
    doc.setTextColor(0, 0, 0);
    doc.text(`Grade: ${metrics.qualityGrade || 'F'}`, pageWidth / 2, yPos, { align: 'center' });
  };

  const generateIssuesPDF = (doc, pageWidth, pageHeight, yPos, data) => {
    doc.setFontSize(16);
    doc.setFont(undefined, 'bold');
    doc.text('🔍 Code Analysis Results', 20, yPos);
    yPos += 10;

    doc.setFillColor(240, 240, 240);
    doc.rect(15, yPos, pageWidth - 30, 25, 'F');
    yPos += 8;

    doc.setFontSize(11);
    doc.setFont(undefined, 'normal');
    const criticalCount = data.critical?.length || 0;
    const warningCount = data.warning?.length || 0;
    const infoCount = data.info?.length || 0;
    const totalIssues = criticalCount + warningCount + infoCount;

    doc.text(`Total Issues Found: ${totalIssues}`, 25, yPos);
    yPos += 7;
    doc.setTextColor(220, 38, 38);
    doc.text(`🔴 Critical: ${criticalCount}`, 25, yPos);
    doc.setTextColor(245, 158, 11);
    doc.text(`⚠️ Warnings: ${warningCount}`, pageWidth / 3 + 10, yPos);
    doc.setTextColor(59, 130, 246);
    doc.text(`ℹ️ Info: ${infoCount}`, 2 * pageWidth / 3 + 10, yPos);
    yPos += 15;

    doc.setTextColor(0, 0, 0);

    if (criticalCount > 0) {
      doc.setFontSize(14);
      doc.setFont(undefined, 'bold');
      doc.setTextColor(220, 38, 38);
      doc.text('🔴 Critical Issues', 20, yPos);
      yPos += 8;

      doc.setFontSize(10);
      doc.setFont(undefined, 'normal');
      doc.setTextColor(0, 0, 0);

      data.critical.slice(0, 5).forEach((issue, index) => {
        if (yPos > pageHeight - 30) {
          doc.addPage();
          yPos = 20;
        }
        doc.text(`${index + 1}. Line ${issue.lineNumber || 'N/A'}:`, 25, yPos);
        yPos += 5;
        const lines = doc.splitTextToSize(issue.description, pageWidth - 50);
        doc.text(lines, 30, yPos);
        yPos += lines.length * 5 + 3;
      });
    }
  };

  const canDownload = (activeView === 'issues' && analysisData) || (activeView === 'metrics' && metricsData);

  return (
    <>
      <Navbar />
      <div className="container">
        <div className="header">
          <h1>☕ Java Code Analyzer Pro</h1>
          <p>AI-Powered Static Code Analysis • Real-Time Feedback</p>
        </div>

        <div className="content">
          <div className="section">
            <div className="section-title">
              <span>📝</span>
              <span>Source Code Editor</span>
            </div>
            <textarea
              value={code}
              onChange={(e) => setCode(e.target.value)}
              placeholder="// Paste your Java code here..."
            />
            <div className="button-group">
              <button onClick={analyzeCode} disabled={loading} className="analyze-btn">
                <span style={{ position: 'relative', zIndex: 1 }}>🔍 Analyze Code</span>
              </button>
              <button onClick={showMetrics} disabled={loading} className="metrics-btn">
                <span style={{ position: 'relative', zIndex: 1 }}>📊 Show Metrics</span>
              </button>
              <button onClick={clearAll} className="clear-btn">
                <span style={{ position: 'relative', zIndex: 1 }}>🗑️ Clear All</span>
              </button>
            </div>
          </div>

          <div className="section">
            <div className="section-title">
              <span>📊</span>
              <span>Analysis Results</span>
            </div>
            <div className="results-container">
              {loading ? (
                <div className="loading">
                  <div className="spinner"></div>
                  <p>Analyzing your code...</p>
                </div>
              ) : activeView === 'issues' ? (
                <ResultsDisplay data={analysisData} stats={stats} />
              ) : (
                <MetricsDashboard data={metricsData} />
              )}
            </div>
            {stats.total > 0 && activeView === 'issues' && (
              <div className="stats">
                <div className="stat-box">
                  <div className="stat-number">{stats.critical}</div>
                  <div className="stat-label">Critical</div>
                </div>
                <div className="stat-box">
                  <div className="stat-number">{stats.warning}</div>
                  <div className="stat-label">Warnings</div>
                </div>
                <div className="stat-box">
                  <div className="stat-number">{stats.info}</div>
                  <div className="stat-label">Suggestions</div>
                </div>
                <div className="stat-box">
                  <div className="stat-number">{stats.total}</div>
                  <div className="stat-label">Total Issues</div>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>

      <button
        className={`download-pdf-btn ${canDownload ? 'show' : ''}`}
        onClick={downloadPDF}
      >
        📥 Download PDF Report
      </button>
    </>
  );
};

export default CodeAnalyzer;